routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('auth.login');
});
//Administrador
 Route::group(['middleware' => ['role:Administrador']], function () {
    Route::get('/Administrador', function () {
     return view('Administrador.Dashboard');
     
 });
 
 Route::resource('Administrador','AdminController');
 });

Route::get('/AdminInforme', function () {
    return view('Administrador.Informe');
});

Route::get('/AdminUsuarios','AdminController@usuarios');

Route::get('/AdminDocumentos','AdminController@documentos');


Route::get('/home', function () {
    return view('home');
});

Route::get('/capturaExp', function () {
    return view('expedientes.create');
});

Route::get('/header', function () {
    return view('layouts.header');
});

Route::get('/perfil', function () {
    return view('users.perfil');
});
Route::get('/tutoria', function () {
    return view('pdf.docencia.tutoria');
});

Route::get('/capacitacion', function () {
    return view('users.capacitacion');
});


// Route::group(['middleware' => ['role:PTC']], function () {
//     Route::get('/Articulo', function () {
//     return view('pdf.academica.articulo');
// });
// });

Route::get('/Articulo-Revista', function () {
    return view('pdf.academica.Articulo_revista');
});
Route::get('/Articulo-Arbitrado', function () {
    return view('pdf.academica.Articulo_Arbitrado');
});


Route::get('/Libro', function () {
    return view('pdf.academica.libro');
});

Route::get('/Informe_tec', function () {
    return view('pdf.academica.informe_tec');
});

Route::get('/Proyecto', function () {
    return view('pdf.academica.proyecto');
});

Route::get('/informes', function () {
    return view('supervisor.informe');
});

Route::get('/consultaInfo', function () {
    return view('supervisor.consulta');
});
Route::group(['middleware' => ['role:Supervisor']], function () {
Route::get('/supervisorDash', function () {
    return view('supervisor.dashboard');

});
Route::get('/supervisorDash','DocumentosController@Supervisor_index')->name('Supervisor.index');
});

Route::get('/asesoria_supervisor/list','DocumentosController@asesoria_supervisor_index');
Route::get('/material_supervisor/list','DocumentosController@material_supervisor_index');
Route::get('/proyecto_supervisor/list','DocumentosController@proyecto_supervisor_index');
Route::get('/difusion_supervisor/list','DocumentosController@difusion_supervisor_index');
Route::get('/revista_supervisor/list','DocumentosController@revista_supervisor_index');
Route::get('/arbitrado_supervisor/list','DocumentosController@arbitrado_supervisor_index');
Route::get('/libro_supervisor/list','DocumentosController@libro_supervisor_index');
Route::get('/tecnico_supervisor/list','DocumentosController@informeTecnico_supervisor_index');
Route::get('/gestion_supervisor/list','DocumentosController@gestionAcademica_supervisor_index');

Route::get('/capacitacion_supervisor/list','DocumentosController@capacitacion_supervisor_index');
// Route::get('/capDiplomado_supervisor/list','DocumentosController@capDiplomado_supervisor_index');
Route::get('/cuerpoAcademico_supervisor/list','DocumentosController@cuerpoAcademico_supervisor_index');
Route::get('/curso_supervisor/list','DocumentosController@curso_supervisor_index');
Route::get('/direccion_supervisor/list','DocumentosController@direccion_supervisor_index');
Route::get('/estadia_supervisor/list','DocumentosController@estadia_supervisor_index');
Route::get('/gestionAcademica_supervisor/list','DocumentosController@gestionAcademica_supervisor_index');
Route::get('/tutoria_supervisor/list','DocumentosController@tutoria_supervisor_index');
Route::get('/tutoriaGrupal_supervisor/list','DocumentosController@tutoriaGrupal_supervisor_index');

//PDF capturaExp
Route::get('/capturaExp', 'PdfController@pdfForm');
Route::post('pdf_download', 'PdfController@pdfDownload');

//PDF Articulo

Route::group(['middleware' => ['role:PTC']], function () {
    Route::get('/articulo', 'PdfController@pdfFormArticulo');
});
Route::post('pdf_download_Articulo', 'PdfController@pdfDownload_Articulo');

//PDF Proyecto
Route::get('/proyecto', 'PdfController@pdfFormProyecto');
Route::post('pdf_download_Proyecto', 'PdfController@pdfDownload_Proyectos');

//PDF Revista
Route::get('/Articulo_revista', 'PdfController@pdfFormRevista');
Route::post('pdf_download_Revista', 'PdfController@pdfDownload_Revista');

//PDF Arbitrado
Route::get('/Articulo_Arbitrado', 'PdfController@pdfFormArbitrado');
Route::post('pdf_download_Arbitrado', 'PdfController@pdfDownload_Arbitrado');

//PDF Libro
Route::get('/libro', 'PdfController@pdfFormLibro');
Route::post('pdf_download_Libro', 'PdfController@pdfDownload_Libro');

//PDF Informe
Route::get('/informe_tec', 'PdfController@pdfFormInforme');
Route::post('pdf_download_Informe', 'PdfController@pdfDownload_Informe');

Route::post('pdf_download_Curso', 'PdfController@pdfDownload_Curso');

Route::post('pdf_download_Tutoria', 'PdfController@pdfDownload_Tutoria');

Route::post('pdf_download_Grupal', 'PdfController@pdfDownload_Tutoria_Grupal');

Route::post('pdf_download_Direccion_Individualizada', 'PdfController@pdfDownload_Direccion_Individualizada');

Route::post('pdf_download_Estadia_Empresa', 'PdfController@pdfDownload_Estadia');

Route::post('pdf_download_Cuerpo_Academico', 'PdfController@pdfDownload_CuerpoAcademico');

//Home
Route::get('/home','HomeController@index');

//Documentos
Route::get('/files/create','DocumentosController@create');
Route::post('/files','DocumentosController@store');

Route::get('/files','DocumentosController@index');
Route::get('/files/{id}','DocumentosController@show');
Route::get('file/download/{file}','DocumentosController@download');


//Busqueda
Route::get('/search','DocumentosController@search');
Route::get('/Adminsearch','AdminController@Adminsearch');
Route::get('/fechas','DocumentosController@fechas');
Route::get('/fechaActual','DocumentosController@fechaActual');
Route::get('/division','AdminController@PorDivision');
Route::get('/nombre','AdminController@PorNombre');
Route::get('/fechasAdmin','AdminController@fechas');
Route::get('/fechaActualAdmin','AdminController@fechaActual');

//Filtro Asesoria
Route::get('/filtro','DocumentosController@busqueda');

//Filtro Busqueda Material
Route::get('/filtroMaterial','DocumentosController@busquedaMaterial');
//Filtro Busqueda Proyecto
Route::get('/filtroProyecto','DocumentosController@busquedaProyecto');
//Filtro Busqueda Revista
Route::get('/filtroRevista','DocumentosController@busquedaRevista');
//Filtro Busqueda Arbitrado
Route::get('/filtroArbitrado','DocumentosController@busquedaArbitrado');
//Filtro Busqueda Libro
Route::get('/filtroLibro','DocumentosController@busquedaLibro');
//Filtro Busqueda InformeTecnico
Route::get('/filtroInformeTecnico','DocumentosController@busquedaInformeTecnico');
//Filtro Busqueda Articulo Difusion
Route::get('/filtroDifusion','DocumentosController@busquedaDifusion');
//Filtro Busqueda Gestion Academica
Route::get('/filtroGestion','DocumentosController@busquedaGestion');
//Filtro Busqueda Tutoria Grupal
Route::get('/filtroGrupal','DocumentosController@busquedaTutoriaG');
//Filtro Busqueda Tutoria Individual
Route::get('/filtroTutoria','DocumentosController@busquedaTutoria');
//Filtro Busqueda Curso
Route::get('/filtroCurso','DocumentosController@busquedaCurso');
//Filtro Busqueda Direccion
Route::get('/filtroDireccion','DocumentosController@busquedaDireccion');
//Filtro Busqueda Estadia
Route::get('/filtroEstadia','DocumentosController@busquedaEstadia');
//Filtro Busqueda Cuerpo Academico
Route::get('/filtroAcademico','DocumentosController@busquedaCuerpo');
//Filtro Busqueda Capacitacion
Route::get('/filtroCapacitacion','DocumentosController@busquedaCapacitacion');
//Resources
Route::resource('archivos','DocumentosController');
Route::resource('usuario','UserController');


//pdfController - Material

Route::post('pdf_download_Material', 'PdfController@pdfDownload_Material');
Route::get('/material/list','PdfController@material_index');
Route::get('/material','PdfController@material_create')->name('material.create');
Route::get('/material/{id}','PdfController@material_show');
Route::post('/material','PdfController@material_store')->name('material.store');
Route::delete('/material/{id}','PdfController@material_destroy')->name('material.destroy');
Route::get('/material/{id}/edit','PdfController@material_edit');
Route::put('/material/{id}','PdfController@material_update')->name('material.update');

Route::get('/material/download/{id}','PdfController@pdfFormMaterial');
Route::get('/material/download/pdf/{file}','PdfController@pdfMaterial');

//pdfController - Asesorias

Route::get('/asesoria/list','PdfController@asesoria_index');
Route::get('/asesoria','PdfController@asesoria_create')->name('asesoria.create');
Route::get('/asesoria/{id}','PdfController@asesoria_show');
Route::post('/asesoria','PdfController@asesoria_store')->name('asesoria.store');


Route::delete('/asesoria/{id}','PdfController@asesoria_destroy')->name('asesoria.destroy');
Route::get('/asesoria/{id}/edit','PdfController@asesoria_edit');
Route::put('/asesoria/{id}','PdfController@asesoria_update')->name('asesoria.update');

Route::get('/asesoria/download/{id}','PdfController@pdfFormAsesoria');
Route::get('/asesoria/download/pdf/{file}','PdfController@pdfAsesoria');



//Seleccion Informe
Route::get('/asesoria/select/{id}','PdfController@InformeAsesoria')->name('asesoria.select');
Route::get('/material/select/{id}','PdfController@InformeMaterial')->name('material.select');

resources/views/Administrador/Dashboard.blade.php
@extends('layouts.admin')

@section('Titulo', 'Repositorio de investigaciones ')

@section('content')
   
<div class="panel-header" style="background: #69bb85;">
        <div class="page-inner py-5">
            <div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
                <div>
                    <h2 class="text-white pb-2 fw-bold">Dashboard</h2>
                    <h5 class="text-white op-7 mb-2">Sistema Repositorio de Producción Académica</h5>
                </div>
              
            </div>
        </div>
    </div>
    <div class="page-inner mt--5">
    
    <!-- Contenido del Dashboard -->
        
 <!-- Tabla Documentos -->
 <div class="row">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                    
                        <div class="card-title">Documentos Material Didactico: {{$material->count()}} </div>
                    </div>
                    <div class="card-body">
                        <div class="d-flex justify-content-right p-3">
                        <table  class="table table-striped table-responsive" >
                            <tr>
                                <th>#</th>
                                <th>Titulo</th>
                                <th>Autor</th>
                                <th>Periodo</th>
                                </tr>
                                @foreach ($material as $key=>$data)
                                <tr>
                                    <td>{{++$key}}</td>
                                    <td>{{$data->titulo}}</td>
                                    <td>{{$data->autor}}</td>
                                    <td>{{$data->cuatrimestre}}</td>
                                    </tr>
                                @endforeach
                            </table>
                        </div>
                    </div>
                </div>
            </div>
                    
 <!-- Tabla Perfiles Activos -->
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">Usuarios Activos: {{$users->count() }}</div>
                    </div>
                    <div class="card-body">
                        <div class="d-flex justify-content-right p-3">
                        <table  class="table table-striped table-responsive" >
                            <tr>
                                <th>#</th>
                                <th>Nombre</th>
                                <th>Role</th>
                                <th>Division</th>
                                </tr>
                                @foreach ($users as $key=>$data)
                                <tr>
                                    <td>{{++$key}}</td>
                                    <td>{{$data->name}}</td>
                                    <td>{{$data->cat_profesor}}</td>
                                    <td>{{$data->division}}</td>                 
                                    </tr>
                                @endforeach
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @endsection

resources/views/Administrador/EditUser.blade.php
@extends('layouts.admin')

@section('Titulo', 'Repositorio de investigaciones ')

@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
    <br>
        <h1 class="display-4">Actualizacion De Usuario</h1>

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br /> 
        @endif
        <form method="post" action="{{ route('Administrador.update', $data->id) }}">
            @method('PATCH') 
            @csrf
            <div class="form-group">

                <label for="first_name">Nombre:</label>
                <input type="text" class="form-control" name="name" value={{ $data->name }} />
            </div>

            <div class="form-group">
                <label for="last_name">Email:</label>
                <input type="text" class="form-control" name="email" value={{ $data->email }} />
            </div>

            <div class="form-group">
                <label for="email">Division:</label>
                <div >
                               
                                <select class="form-control custom-select" id="inputGroupSelect01"  name="division">
                                    <option value="Económico-Administrativa">Económico-Administrativa</option>
                                    <option value="Gastronomia">Gastronomia</option>
                                    <option value="Turismo">Turismo</option>
                                    <option value="Ingeniería y Tecnología">Ingeniería y Tecnología</option>
                                    </select>
                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
            </div>
            <div class="form-group">
                <label for="programa">Programa:</label>
                <input type="text" class="form-control" name="programa" value={{ $data->programa }} />
            </div>
            <div class="form-group">
                <label for="sei">SEI:</label>
                <input type="text" class="form-control" name="sei" value={{ $data->sei }} />
            </div>
            <div class="form-group">
                <label for="prodep">PRODEP:</label>
                <input type="text" class="form-control" name="prodep" value={{ $data->prodep }} />
            </div>
            <div class="form-group">
                <label for="prodep">Grado:</label>
                <input type="text" class="form-control" name="grado" value={{ $data->grado }} />
            </div>
            <div class="form-group">
                <label for="curp">CURP:</label>
                <input type="text" class="form-control" name="curp" value={{ $data->curp }} />
            </div>
            <div class="form-group">
                <label for="rfc">RFC:</label>
                <input type="text" class="form-control" name="rfc" value={{ $data->rfc }} />
            </div>
            <div class="form-group">
                <label for="Role">Role:</label>
                <input type="text" class="form-control" name="cat_profesor" value={{ $data->cat_profesor }} />
            </div>
            <div class="form-group">
                <label for="password">Contraseña:</label>
                <input type="text" class="form-control" name="password" value={{ $data->password }} />
            </div>
            <button type="submit" class="btn btn-primary" style="background: #69bb85!important; border-color:#69bb85!important;">Actualizar</button>
        </form>
    </div>
</div>
@endsection

resources/views/Administrador/GestionUsuarios.blade.php
@extends('layouts.admin')

@section('Titulo', 'Repositorio de investigaciones ')

@section('content')


<!-- Bootstrap CSS -->
<div class="panel-header colorut" >
		<div class="page-inner py-5">
			<div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
			    <div>
			        <h2 class="text-black pb-2 fw-bold">Historial de Usuarios</h2>
		        </div>		
	        </div>
		</div>
    </div>
    
	<div class="page-inner mt--5">
   			 <div class="container">
             <h4>Buscar Por Nombre y Division</h4>	
             <div class="d-block">
              <!--Filtro por Division--->
                  <form action="/division" method="GET" class="form-group  col-md-5" style="display: inline-block;" >
                  <div style="display:flex; align-items: baseline;">     
                    <label style="margin-right: 0.2rem;">Division:</label>     
                    <select class="custom-select border border-secondary" id="inputGroupSelect01" style="display: inline-block; margin-right: 0.5rem;" name="division">
                                    <option value="Económico-Administrativa">Económico-Administrativa</option>
                                    <option value="Gastronomia">Gastronomia</option>
                                    <option value="Turismo">Turismo</option>
                                    <option value="Ingeniería y Tecnología">Ingeniería y Tecnología</option>  
                                              </select> 
                                              
                    <input type="submit"  class="btn btn-default" style="background: #69bb85!important; border-color:#69bb85!important;" value="filtrar">
                    </div>
                </form>
                <!-- Fin de filtro -->
            
            <!--Filtro por Nombre--->
               
                <form action="/nombre"  method="GET"  style="display: inline-block;"  class="form-group  col-md-5" >
                <label style="margin-right: 0.2rem;">Nombre:  
                   <input type="text" class="form-control border border-secondary" style="display: inline-block; margin-right: 0.2rem;" placeholder="Nombre" name="nombre"> 
                   <input type="submit"  class="btn btn-default"  style="background: #69bb85!important; border-color:#69bb85!important;"value="filtrar"></label>
    </form>
    <!-- Fin de filtro -->
    </div>
                  </div>  
                  <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">Usuarios Activos: {{$users->count() }}</div>
                    </div>
                    <div class="card-body">
                        <div class="d-flex justify-content-right p-3">
                        <table  class="table table-striped table-responsive" >

          <tr>
              <th>#</th>
              <th>Nombre</th>
              <th>Role</th>
              <th>Division</th>
              <th>Datos</th>
              <th>Actualizar Datos</th>
              <th>Eliminar Usuario</th>
             
            </tr>
                @foreach ($users as $key=>$data)
                <tr>
                    <td>{{++$key}}</td>
                    <td>{{$data->name}}</td>
                    <td>{{$data->cat_profesor}}</td>
                    <td>{{$data->division}}</td>
                   
                    <td><a class="btn btn-success" style="background: #69bb85!important; border-color:#69bb85!important;" href="{{ route('Administrador.show', $data->id) }}">Ver</a> </td>
                    <td><a class="btn btn-warning" style="background: #69bb85!important; border-color:#69bb85!important;" href="{{ route('Administrador.edit', $data->id) }}">Actualizar</a> </td>
                    <td>
                        <form action="{{route('Administrador.destroy', $data->id)}}"  method="POST"> 
                        @method("DELETE")
                        @csrf
                       <input type="submit" class="btn btn-danger" style="background: #69bb85!important; border-color:#69bb85!important;" value="Eliminar">
                       </form>
                    </td>
                    </tr>
                @endforeach
      </table>
@endsection

resources/views/Administrador/ViewUser.blade.php
@extends('layouts.admin')

@section('Titulo', 'Repositorio de investigaciones ')

@section('content')

<table class="table table-hover table-dark">                   
						<div class="card text-center">
					
						<div class="card-footer text-muted">
							<div class="accordion accordion-secondary">
								<div class="card">
									<div class="card-header collapsed" id="headingOne" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
										<div class="span-icon">
											<div class="flaticon-box-1"></div>
										</div>
										<div class="span-title">
											Nombre de  Usuario
										</div>
										<div class="span-mode"></div>
									</div>
									<div id="collapseOne" class="collapse " aria-labelledby="headingOne" data-parent="#accordion">
										<div class="card-body">
                                        {{$data->name}}
										</div>
									</div>
								</div>
								<div class="card">
									<div class="card-header collapsed" id="headingTwo" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
										<div class="span-icon">
											<div class="flaticon-box-1"></div>
										</div>
										<div class="span-title">
											Password
										</div>
										<div class="span-mode"></div>
									</div>
									<div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
										<div class="card-body">
                                        {{$data->password}}									</div>
									</div>
								</div>
								<div class="card">
									<div class="card-header collapsed" id="headingThree" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
										<div class="span-icon">
											<div class="flaticon-box-1"></div>
										</div>
										<div class="span-title">
											División
										</div>
										<div class="span-mode"></div>
									</div>
									<div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
										<div class="card-body">
                                        {{$data->division}}
										</div>
									</div>
								</div>
							</div>
							<!-- segunda secion -->

							<div class="accordion accordion-secondary">
								<div class="card">
									<div class="card-header collapsed" id="headingfour" data-toggle="collapse" data-target="#collapsefour" aria-expanded="false" aria-controls="collapsefour">
										<div class="span-icon">
											<div class="flaticon-box-1"></div>
										</div>
										<div class="span-title">
											CURP
										</div>
										<div class="span-mode"></div>
									</div>
									<div id="collapsefour" class="collapse" aria-labelledby="headingfour" data-parent="#accordion">
										<div class="card-body">
                                        {{$data->curp}}
										</div>
									</div>
								</div>
								<div class="card">
									<div class="card-header collapsed" id="headingfive" data-toggle="collapse" data-target="#collapsefive" aria-expanded="false" aria-controls="collapsefive">
										<div class="span-icon">
											<div class="flaticon-box-1"></div>
										</div>
										<div class="span-title">
											RFC
										</div>
										<div class="span-mode"></div>
									</div>
									<div id="collapsefive" class="collapse" aria-labelledby="headingfive" data-parent="#accordion">
										<div class="card-body">
                                        {{$data->rfc}}
										</div>
									</div>
								</div>
								
							<!-- tercera parte -->
							<div class="accordion accordion-secondary">
								<div class="card">
									<div class="card-header collapsed" id="headingseven" data-toggle="collapse" data-target="#collapseseven" aria-expanded="false" aria-controls="collapseseven">
										<div class="span-icon">
											<div class="flaticon-box-1"></div>
										</div>
										<div class="span-title">
											Programa educativo   
										</div>
										<div class="span-mode"></div>
									</div>
									<div id="collapseseven" class="collapse" aria-labelledby="headingseven" data-parent="#accordion">
										<div class="card-body">
										{{$data->programa}}
										</div>
									</div>
								</div>
								<div class="card">
									<div class="card-header collapsed" id="headingeight" data-toggle="collapse" data-target="#collapseeight" aria-expanded="false" aria-controls="collapseeight">
										<div class="span-icon">
											<div class="flaticon-box-1"></div>
										</div>
										<div class="span-title">
											Cuerpo Académico
										</div>
										<div class="span-mode"></div>
									</div>
									<div id="collapseeight" class="collapse" aria-labelledby="headingeight" data-parent="#accordion">
										<div class="card-body">
                                        {{$data->cat_profesor}}
										</div>
									</div>
								</div>
								<div class="card">
									<div class="card-header collapsed" id="headingnine" data-toggle="collapse" data-target="#collapsenine" aria-expanded="false" aria-controls="collapsenine">
										<div class="span-icon">
											<div class="flaticon-box-1"></div>
										</div>
										<div class="span-title">
											Nivel en el SEI
										</div>
										<div class="span-mode"></div>
									</div>
									<div id="collapsenine" class="collapse" aria-labelledby="headingnine" data-parent="#accordion">
										<div class="card-body">
										{{$data->sei}}
										</div>
									</div>
								</div>
							</div>
							<!-- Cuarta parte _-->
							<div class="accordion accordion-secondary">
								<div class="card">
									<div class="card-header collapsed" id="headingten" data-toggle="collapse" data-target="#collapseten" aria-expanded="false" aria-controls="collapseten">
										<div class="span-icon">
											<div class="flaticon-box-1"></div>
										</div>
										<div class="span-title">
											Perfil  PRODEP
										</div>
										<div class="span-mode"></div>
									</div>
									<div id="collapseten" class="collapse" aria-labelledby="headingten" data-parent="#accordion">
										<div class="card-body">
										{{$data->prodep}}
										</div>
									</div>
								</div>
								<div class="card">
									<div class="card-header collapsed" id="headingeleven" data-toggle="collapse" data-target="#collapseeleven" aria-expanded="false" aria-controls="collapseeleven">
										<div class="span-icon">
											<div class="flaticon-box-1"></div>
										</div>
										<div class="span-title">
											Grado de estudios
										</div>
										<div class="span-mode"></div>
									</div>
									<div id="collapseeleven" class="collapse" aria-labelledby="headingeleven" data-parent="#accordion">
										<div class="card-body">
										{{$data->grado}}
										</div>
									</div>
								</div>
								<div class="card">
									<div class="card-header collapsed" id="headingtwelve" data-toggle="collapse" data-target="#collapsetwelve" aria-expanded="false" aria-controls="collapsetwelve">
										<div class="span-icon">
											<div class="flaticon-box-1"></div>
										</div>
										<div class="span-title">
											Especialidad
										</div>
										<div class="span-mode"></div>
									</div>
									<div id="collapsetwelve" class="collapse" aria-labelledby="headingtwelve" data-parent="#accordion">
										<div class="card-body">
										{{$data->especialidad}}
										</div>
									</div>
								</div>
							</div>
						</div>
					</table>
       
  @endsection
  